version: '3'
services:
  db:
    image: mysql:5.7
    container_name: helpdesk_db
    environment:
      MYSQL_ROOT_PASSWORD: helpdesk
      MYSQL_DATABASE: helpdesk
      MYSQL_USER: helpdesk
      MYSQL_PASSWORD: helpdesk
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: helpdesk_pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
