---- Types

CREATE TYPE user_role as ENUM('employee', 'executor', 'admin');
CREATE TYPE ticket_status as ENUM('created','assigned','accepted','done');

---- Tables

CREATE TABLE users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	username varchar(128) NOT NULL UNIQUE,
	password varchar(255) NOT NULL,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	role user_role NOT NULL
);

CREATE TABLE companies (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	itn varchar(20) NOT NULL,
	name varchar(255) NOT NULL,
	description varchar(255) DEFAULT NULL,
	slug varchar(255) NOT NULL
);

CREATE TABLE departments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	company_id BIGINT NOT NULL,
	name varchar(255) NOT NULL,
	description varchar(255) DEFAULT NULL,
	address varchar(255) NOT NULL,
	contacts varchar(255) NOT NULL
);

CREATE TABLE tickets (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	user_id BIGINT NOT NULL,
	title varchar(255) NOT NULL,
	description varchar(255) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status ticket_status NOT NULL DEFAULT 'created'
);
